language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: loan-issuance
  api_key:
    secure: dOQgKEAcW+jQ1EJEBQll/+58/ISRZB56QvOeCBK9ST4nAaW0uiyvbnNyHNF1yoezNhIBgK96w7hRTBYNME2XM5simKiHV3A7ZOjDeXN1NWamAEQALCkEqMjPlmiEfSwWE51UsFSo/FPI/U9CwfVyNVNEmJOFBbLwNyjWc54rreeNlX0UKNuO/fCY4dNei42YKhQ93Dh7u9nSrC6wczwNLa55hGHtmCq+ItlYfRmtuQ3955KWw8tLuQFaNlRDHHBAU1+P0q3mrWtnK8WxijAD85O14gNruLzvPsldZV3ThyR8OS9Il2XmsNCLipCJ7+0GvgYTWm3wY6nR0Z7um4wUu+5SDfrVE2Mqyt5lYkRKg317h8LlTmYnI1zqvkKQOUNPpACaE0AkuNhnkHnG8j0l5FWuyunGbJNp11E31/gDKUdK6aWrQja8buOE+tAz2U0M7hF6kqiy2f+/56rS5Jp/6bx/Cz4LgmCImUKcdQk/QbXFbopJxWhluvmG7k+ag7P0SxdljQQjx69w+CRKF+CNrT1u480250tADDTCtiRnBE+bvg+K4fcBKPxFG3+BOU69WeLg3y4aCgnB9J2VL9n6Gu8ck+tL0rkjZHNGF1cBMCHcR5hXDOr7jy2T6YQxoP2XL8buSPK+OfqdTKMJtr5fQfVd/6ez0E+eGSQxgx7GOU0=