language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: loan-issuance
  api_key:
    secure: QtaZ071M1fUAXc/OLiHrxvFODbgzCPguMq+8EM5P6Fn0spXMwN/wkKZkPwUl0dAdeuVEcQkkzRSqHcU/IomV9pPZf5VfV+YqFkI912qBS0QmMpKXjZZyF0XzciWw8yvoA6g920gfla45lDllAVS8n3iMAyWrBVZh7WZe+7cbz56Yp5GkQDgQVgqmfN7TAxZP5UIHj2JmqeLPf3G7UVaxbSRf2Qsucqa386/cdxJ9bZhWPKfjK/jrXE+T/e0uNNYCoVBEfljswIgBf3VYz0kXRJ/rroj/B7WtSYk3xFCIo/uoeLICUwooPT9ud+90bOQuocUngxV8mdPMCZYr0vUzrM1IlW63Qv3FUjBPxZqHM0YapuwMPzunu3ldllCeujmIGTYMM7ui26/A37Zr/q8J41975xTWBH5TKu2qacg6kmxBsdBRBrrSujs1o14WSFcDiuMRwEi0iz0gf58vgIxP2ULm1aJ58/81oWg21GxyTns9s5bloEEtWAIaD7jg+q3gl8GctyG9HpDtc6etxlTXolTEunwn2yiQkmmgcTLooZWZUaGLrFDSzASk5gbQZbLVm9RaVq+m/znQV36fitCx0JoxyJn941jeu+XoDB8dhs2V3jp6Gj6NDI8LMj/AlQPG2/iJru5YlZxXU/+fiq0QhpOqP7YHJkb3dUqlgXJoIfA=
